
name: terraform-environments-action
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      tf_dir:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Test Build
        run: |
          pwd
          ls -la
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing Repo
        run: |
          pwd 
          ls -la
    